export default {
    "palette": {
        "themeDarker": "#5b1519",
        "themeDark": "#7c1d21",
        "themeDarkAlt": "#932227",
        "themePrimary": "#006bd6",
        "themeSecondary": "#ae383e",
        "themeTertiary": "#c86c70",
        "themeLight": "#e3afb2",
        "themeLighter": "#f0d3d4",
        "themeLighterAlt": "#fbf4f4",
        "black": "#000000",
        "blackTranslucent40": "rgba(0,0,0,.4)",
        "neutralDark": "#201f1e",
        "neutralPrimary": "#323130",
        "neutralPrimaryAlt": "#3b3a39",
        "neutralSecondary": "#605e5c",
        "neutralSecondaryAlt": "#8a8886",
        "neutralTertiary": "#a19f9d",
        "neutralTertiaryAlt": "#c8c6c4",
        "neutralQuaternary": "#d2d0ce",
        "neutralQuaternaryAlt": "#e1dfdd",
        "neutralLight": "#edebe9",
        "neutralLighter": "#f3f2f1",
        "neutralLighterAlt": "#faf9f8",
        "accent": "#ca5010",
        "white": "#ffffff",
        "whiteTranslucent40": "rgba(255, 255, 255, 0.40)",
        "yellowDark": "#d29200",
        "yellow": "#ffb900",
        "yellowLight": "#fff100",
        "orange": "#d83b01",
        "orangeLight": "#ea4300",
        "orangeLighter": "#ff8c00",
        "redDark": "#a4262c",
        "red": "#e81123",
        "magentaDark": "#5c005c",
        "magenta": "#b4009e",
        "magentaLight": "#e3008c",
        "purpleDark": "#32145a",
        "purple": "#5c2d91",
        "purpleLight": "#b4a0ff",
        "blueDark": "#002050",
        "blueMid": "#00188f",
        "blue": "#0078d4",
        "blueLight": "#00bcf2",
        "tealDark": "#004b50",
        "teal": "#008272",
        "tealLight": "#00b294",
        "greenDark": "#004b1c",
        "green": "#107c10",
        "greenLight": "#bad80a",
        "primaryBackground": "#ffffff",
        "primaryText": "#333333",
        "HyperlinkActive": "#5b1519",
        "CommandLinksPressed": "#5b1519",
        "NavigationPressed": "#5b1519",
        "EmphasisHoverBorder": "#5b1519",
        "TopBarPressedText": "#5b1519",
        "HeaderNavigationPressedText": "#5b1519",
        "Hyperlinkfollowed": "#5b1519",
        "EmphasisHoverBackground": "#7c1d21",
        "EmphasisBorder": "#7c1d21",
        "AccentText": "#a4262c",
        "CommandLinksHover": "#a4262c",
        "RowAccent": "#a4262c",
        "NavigationAccent": "#a4262c",
        "NavigationHover": "#a4262c",
        "EmphasisBackground": "#a4262c",
        "HeaderNavigationHoverText": "#a4262c",
        "HeaderNavigationSelectedText": "#a4262c",
        "SuiteBarBackground": "#a4262c",
        "Hyperlink": "#a4262c",
        "ContentAccent1": "#a4262c",
        "AccentLines": "#ae383e",
        "HeaderAccentLines": "#ae383e",
        "ButtonPressedBorder": "#ae383e",
        "SuiteBarHoverBackground": "#c86c70",
        "StrongLines": "#e3afb2",
        "HeaderStrongLines": "#e3afb2",
        "SuiteBarHoverText": "#e3afb2",
        "ButtonPressedBackground": "#e3afb2",
        "ButtonHoverBorder": "#e3afb2",
        "ButtonHoverBackground": "#f0d3d4",
        "SelectionBackground": "rgba(227, 175, 178, 0.50)",
        "HoverBackground": "rgba(240, 211, 212, 0.50)",
        "NavigationHoverBackground": "rgba(240, 211, 212, 0.50)",
        "PageBackground": "#ffffff",
        "EmphasisText": "#ffffff",
        "SuiteBarText": "#ffffff",
        "TileText": "#ffffff",
        "BackgroundOverlay": "rgba(255, 255, 255, 0.85)",
        "HeaderBackground": "rgba(255, 255, 255, 0.85)",
        "FooterBackground": "rgba(255, 255, 255, 0.85)",
        "DisabledBackground": "#faf9f8",
        "HeaderDisabledBackground": "#faf9f8",
        "ButtonBackground": "#faf9f8",
        "ButtonDisabledBackground": "#faf9f8",
        "SubtleEmphasisBackground": "#f3f2f1",
        "DialogBorder": "#f3f2f1",
        "NavigationSelectedBackground": "rgba(237, 235, 233, 0.78)",
        "TopBarBackground": "rgba(237, 235, 233, 0.78)",
        "DisabledLines": "#edebe9",
        "HeaderDisabledLines": "#edebe9",
        "ButtonDisabledBorder": "#edebe9",
        "SuiteBarDisabledText": "#edebe9",
        "SubtleLines": "#c8c6c4",
        "HeaderSubtleLines": "#c8c6c4",
        "ButtonGlyphDisabled": "#c8c6c4",
        "DisabledText": "#a19f9d",
        "CommandLinksDisabled": "#a19f9d",
        "HeaderDisableText": "#a19f9d",
        "ButtonDisabledText": "#a19f9d",
        "Lines": "#a19f9d",
        "HeaderLines": "#a19f9d",
        "ButtonBorder": "#a19f9d",
        "SubtleBodyText": "#8a8886",
        "HeaderSubtleText": "#8a8886",
        "CommandLinks": "#605e5c",
        "Navigation": "#605e5c",
        "SubtleEmphasisText": "#605e5c",
        "TopBarText": "#605e5c",
        "HeaderNavigationText": "#605e5c",
        "ButtonGlyph": "#605e5c",
        "BodyText": "#323130",
        "WebPartHeading": "#323130",
        "HeaderText": "#323130",
        "ButtonText": "#323130",
        "ButtonGlyphActive": "#323130",
        "TopBarHoverText": "#323130",
        "StrongBodyText": "#201f1e",
        "SiteTitle": "#201f1e",
        "CommandLinksSecondary": "#201f1e",
        "SubtleEmphasisCommandLinks": "#201f1e",
        "HeaderSiteTitle": "#201f1e",
        "TileBackgroundOverlay": "rgba(0, 0, 0, 0.50)",
        "ContentAccent2": "#00485b",
        "ContentAccent3": "#288054",
        "ContentAccent4": "#767956",
        "ContentAccent5": "#ed0033",
        "ContentAccent6": "#682a7a",
        "backgroundOverlay": "rgba(255, 255, 255, 0.85)",
        "themeAccent": "#a4262c",
        "themeAccentTranslucent10": "rgba(164, 38, 44, 0.10)",
        "suiteBarBackground": "#a4262c",
        "suiteBarText": "#ffffff",
        "suiteBarDisabledText": "#edebe9",
        "topBarBackground": "rgba(237, 235, 233, 0.78)",
        "topBarText": "#605e5c",
        "topBarHoverText": "#323130",
        "dialogBorder": "#f3f2f1"
    },
    "effects": {
        "elevation4": "0 1.6px 3.6px 0 rgba(0, 0, 0, 0.132), 0 0.3px 0.9px 0 rgba(0, 0, 0, 0.108)",
        "elevation8": "0 3.2px 7.2px 0 rgba(0, 0, 0, 0.132), 0 0.6px 1.8px 0 rgba(0, 0, 0, 0.108)",
        "elevation16": "0 6.4px 14.4px 0 rgba(0, 0, 0, 0.132), 0 1.2px 3.6px 0 rgba(0, 0, 0, 0.108)",
        "elevation64": "0 25.6px 57.6px 0 rgba(0, 0, 0, 0.22), 0 4.8px 14.4px 0 rgba(0, 0, 0, 0.18)",
        "roundedCorner2": "2px",
        "roundedCorner4": "4px",
        "roundedCorner6": "6px"
    },
    "fonts": {
        "tiny": {
            "fontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
            "MozOsxFontSmoothing": "grayscale",
            "WebkitFontSmoothing": "antialiased",
            "fontSize": "10px",
            "fontWeight": 400
        },
        "xSmall": {
            "fontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
            "MozOsxFontSmoothing": "grayscale",
            "WebkitFontSmoothing": "antialiased",
            "fontSize": "10px",
            "fontWeight": 400
        },
        "small": {
            "fontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
            "MozOsxFontSmoothing": "grayscale",
            "WebkitFontSmoothing": "antialiased",
            "fontSize": "12px",
            "fontWeight": 400
        },
        "smallPlus": {
            "fontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
            "MozOsxFontSmoothing": "grayscale",
            "WebkitFontSmoothing": "antialiased",
            "fontSize": "12px",
            "fontWeight": 400
        },
        "medium": {
            "fontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
            "MozOsxFontSmoothing": "grayscale",
            "WebkitFontSmoothing": "antialiased",
            "fontSize": "14px",
            "fontWeight": 400
        },
        "mediumPlus": {
            "fontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
            "MozOsxFontSmoothing": "grayscale",
            "WebkitFontSmoothing": "antialiased",
            "fontSize": "16px",
            "fontWeight": 400
        },
        "large": {
            "fontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
            "MozOsxFontSmoothing": "grayscale",
            "WebkitFontSmoothing": "antialiased",
            "fontSize": "18px",
            "fontWeight": 400
        },
        "xLarge": {
            "fontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
            "MozOsxFontSmoothing": "grayscale",
            "WebkitFontSmoothing": "antialiased",
            "fontSize": "20px",
            "fontWeight": 600
        },
        "xLargePlus": {
            "fontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
            "MozOsxFontSmoothing": "grayscale",
            "WebkitFontSmoothing": "antialiased",
            "fontSize": "24px",
            "fontWeight": 600
        },
        "xxLarge": {
            "fontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
            "MozOsxFontSmoothing": "grayscale",
            "WebkitFontSmoothing": "antialiased",
            "fontSize": "28px",
            "fontWeight": 600
        },
        "xxLargePlus": {
            "fontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
            "MozOsxFontSmoothing": "grayscale",
            "WebkitFontSmoothing": "antialiased",
            "fontSize": "32px",
            "fontWeight": 600
        },
        "superLarge": {
            "fontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
            "MozOsxFontSmoothing": "grayscale",
            "WebkitFontSmoothing": "antialiased",
            "fontSize": "42px",
            "fontWeight": 600
        },
        "mega": {
            "fontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
            "MozOsxFontSmoothing": "grayscale",
            "WebkitFontSmoothing": "antialiased",
            "fontSize": "68px",
            "fontWeight": 600
        }
    },
    "spacing": {
        "s2": "4px",
        "s1": "8px",
        "m": "16px",
        "l1": "20px",
        "l2": "32px"
    },
    "isInverted": false,
    "disableGlobalClassNames": false,
    "semanticColors": {
        "bodyBackground": "#ffffff",
        "bodyFrameBackground": "#ffffff",
        "accentButtonText": "#ffffff",
        "buttonBackground": "#ffffff",
        "primaryButtonText": "#ffffff",
        "primaryButtonTextHovered": "#ffffff",
        "primaryButtonTextPressed": "#ffffff",
        "inputBackground": "#ffffff",
        "inputForegroundChecked": "#ffffff",
        "listBackground": "#ffffff",
        "menuBackground": "#ffffff",
        "cardStandoutBackground": "#ffffff",
        "bodyTextChecked": "#000000",
        "buttonTextCheckedHovered": "#000000",
        "link": "#a4262c",
        "primaryButtonBackground": "#a4262c",
        "inputBackgroundChecked": "#a4262c",
        "inputIcon": "#a4262c",
        "inputFocusBorderAlt": "#a4262c",
        "menuIcon": "#a4262c",
        "menuHeader": "#a4262c",
        "accentButtonBackground": "#ca5010",
        "primaryButtonBackgroundPressed": "#7c1d21",
        "inputBackgroundCheckedHovered": "#7c1d21",
        "inputIconHovered": "#7c1d21",
        "linkHovered": "#5b1519",
        "primaryButtonBackgroundHovered": "#932227",
        "inputPlaceholderBackgroundChecked": "#f0d3d4",
        "bodyBackgroundChecked": "#edebe9",
        "bodyFrameDivider": "#edebe9",
        "bodyDivider": "#edebe9",
        "variantBorder": "#edebe9",
        "buttonBackgroundCheckedHovered": "#edebe9",
        "buttonBackgroundPressed": "#edebe9",
        "listItemBackgroundChecked": "#edebe9",
        "listHeaderBackgroundPressed": "#edebe9",
        "menuItemBackgroundPressed": "#edebe9",
        "menuItemBackgroundChecked": "#edebe9",
        "bodyBackgroundHovered": "#f3f2f1",
        "buttonBackgroundHovered": "#f3f2f1",
        "buttonBackgroundDisabled": "#f3f2f1",
        "buttonBorderDisabled": "#f3f2f1",
        "primaryButtonBackgroundDisabled": "#f3f2f1",
        "disabledBackground": "#f3f2f1",
        "listItemBackgroundHovered": "#f3f2f1",
        "listHeaderBackgroundHovered": "#f3f2f1",
        "menuItemBackgroundHovered": "#f3f2f1",
        "primaryButtonTextDisabled": "#d2d0ce",
        "disabledSubtext": "#d2d0ce",
        "listItemBackgroundCheckedHovered": "#e1dfdd",
        "disabledBodyText": "#a19f9d",
        "variantBorderHovered": "#a19f9d",
        "buttonTextDisabled": "#a19f9d",
        "inputIconDisabled": "#a19f9d",
        "disabledText": "#a19f9d",
        "bodyText": "#323130",
        "actionLink": "#323130",
        "buttonText": "#323130",
        "inputBorderHovered": "#323130",
        "inputText": "#323130",
        "listText": "#323130",
        "menuItemText": "#323130",
        "bodyStandoutBackground": "#faf9f8",
        "defaultStateBackground": "#faf9f8",
        "actionLinkHovered": "#201f1e",
        "buttonTextHovered": "#201f1e",
        "buttonTextChecked": "#201f1e",
        "buttonTextPressed": "#201f1e",
        "inputTextHovered": "#201f1e",
        "menuItemTextHovered": "#201f1e",
        "bodySubtext": "#605e5c",
        "focusBorder": "#605e5c",
        "inputBorder": "#605e5c",
        "smallInputBorder": "#605e5c",
        "inputPlaceholderText": "#605e5c",
        "buttonBorder": "#8a8886",
        "disabledBodySubtext": "#c8c6c4",
        "disabledBorder": "#c8c6c4",
        "buttonBackgroundChecked": "#c8c6c4",
        "menuDivider": "#c8c6c4",
        "cardShadow": "0 1.6px 3.6px 0 rgba(0, 0, 0, 0.132), 0 0.3px 0.9px 0 rgba(0, 0, 0, 0.108)",
        "cardShadowHovered": "0 0 1px #a19f9d",
        "primaryButtonBorder": "transparent",
        "errorText": "#a4262c",
        "messageText": "#323130",
        "messageLink": "#005A9E",
        "messageLinkHovered": "#004578",
        "infoIcon": "#605e5c",
        "errorIcon": "#A80000",
        "blockingIcon": "#FDE7E9",
        "warningIcon": "#797775",
        "severeWarningIcon": "#D83B01",
        "successIcon": "#107C10",
        "infoBackground": "#f3f2f1",
        "errorBackground": "#FDE7E9",
        "blockingBackground": "#FDE7E9",
        "warningBackground": "#FFF4CE",
        "severeWarningBackground": "#FED9CC",
        "successBackground": "#DFF6DD",
        "warningHighlight": "#ffb900",
        "successText": "#107C10",
        "listTextColor": "#323130",
        "warningText": "#323130"
    },
    "mode": "light"
}